CREATE TABLE IF NOT EXISTS coupons (
    Id SERIAL PRIMARY KEY,
    Code VARCHAR(50) UNIQUE NOT NULL,
    DiscountPercentage DECIMAL(18,2) NULL,
    DiscountAmount DECIMAL(18,2) NULL,
    ValidFrom TIMESTAMP NULL,
    ValidUntil TIMESTAMP NULL,
    MaxUses INT NULL,
    CurrentUses INT NOT NULL DEFAULT 0,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
