CREATE TABLE IF NOT EXISTS vehicles (
    Id SERIAL PRIMARY KEY,
    PlateNumber VARCHAR(20) UNIQUE NOT NULL,
    Model VARCHAR(100) NOT NULL,
    Capacity DECIMAL(10,2) NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS drivers (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    LicenseNumber VARCHAR(50) UNIQUE NOT NULL,
    Phone VARCHAR(20) NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS delivery_routes (
    Id SERIAL PRIMARY KEY,
    Date DATE NOT NULL,
    DriverId INT NOT NULL REFERENCES drivers(Id),
    VehicleId INT NOT NULL REFERENCES vehicles(Id),
    Status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS route_stops (
    Id SERIAL PRIMARY KEY,
    DeliveryRouteId INT NOT NULL REFERENCES delivery_routes(Id) ON DELETE CASCADE,
    OrderId INT NOT NULL,
    StopOrder INT NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    EstimatedTime TIMESTAMP NULL
);
