-- Migration to add Credit Purchases and Accounts Payable

ALTER TABLE Purchases ADD COLUMN IF NOT EXISTS PaymentType VARCHAR(20) NOT NULL DEFAULT 'CASH';
ALTER TABLE Purchases ADD COLUMN IF NOT EXISTS AmountPaid DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE Purchases ADD COLUMN IF NOT EXISTS Status VARCHAR(20) NOT NULL DEFAULT 'PAID';

CREATE TABLE IF NOT EXISTS AccountsPayable (
    Id SERIAL PRIMARY KEY,
    PurchaseId INT REFERENCES Purchases(Id),
    SupplierId INT REFERENCES Suppliers(Id),
    TotalDebt DECIMAL(12,2) NOT NULL,
    AmountPaid DECIMAL(12,2) NOT NULL DEFAULT 0,
    Balance DECIMAL(12,2) NOT NULL,
    DueDate TIMESTAMP,
    Status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS PayablePayments (
    Id SERIAL PRIMARY KEY,
    AccountId INT REFERENCES AccountsPayable(Id),
    UserId INT REFERENCES Users(Id),
    Amount DECIMAL(12,2) NOT NULL,
    PaymentDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Notes VARCHAR(255),
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);
