ALTER TABLE Sales ADD COLUMN IF NOT EXISTS PaymentType VARCHAR(20) NOT NULL DEFAULT 'CASH';
ALTER TABLE Sales ADD COLUMN IF NOT EXISTS AmountTendered DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE Sales ADD COLUMN IF NOT EXISTS Change DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE Sales ADD COLUMN IF NOT EXISTS Status VARCHAR(20) NOT NULL DEFAULT 'PAID';

CREATE TABLE IF NOT EXISTS AccountsReceivable (
    Id SERIAL PRIMARY KEY,
    SaleId INT REFERENCES Sales(Id),
    CustomerId INT REFERENCES Customers(Id),
    TotalDebt DECIMAL(12,2) NOT NULL,
    AmountPaid DECIMAL(12,2) NOT NULL DEFAULT 0,
    Balance DECIMAL(12,2) NOT NULL,
    DueDate TIMESTAMP,
    Status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS ReceivablePayments (
    Id SERIAL PRIMARY KEY,
    AccountId INT REFERENCES AccountsReceivable(Id),
    UserId INT REFERENCES Users(Id),
    Amount DECIMAL(12,2) NOT NULL,
    PaymentDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Notes VARCHAR(255),
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS Notifications (
    Id SERIAL PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Message VARCHAR(255) NOT NULL,
    Type VARCHAR(20) NOT NULL DEFAULT 'INFO',
    ReferenceId INT,
    IsResolved BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);
