-- Missing Tables and Columns to match API Models

-- Alter Users Table
ALTER TABLE Users
ADD COLUMN IF NOT EXISTS JobTitle VARCHAR(100),
ADD COLUMN IF NOT EXISTS DocumentId VARCHAR(50),
ADD COLUMN IF NOT EXISTS BaseBonus DECIMAL(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS IncomeTaxPercentage DECIMAL(5,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS IsAdmin BOOLEAN DEFAULT FALSE;

-- Chart of Accounts
CREATE TABLE IF NOT EXISTS Accounts (
    Id SERIAL PRIMARY KEY,
    Code VARCHAR(20) NOT NULL UNIQUE,
    Name VARCHAR(100) NOT NULL,
    Type VARCHAR(50) NOT NULL,
    ParentAccountId INT REFERENCES Accounts(Id),
    Level INT NOT NULL DEFAULT 1,
    AllowsTransactions BOOLEAN NOT NULL DEFAULT TRUE,
    Description VARCHAR(255),
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

-- Bank Accounts
CREATE TABLE IF NOT EXISTS BankAccounts (
    Id SERIAL PRIMARY KEY,
    BankName VARCHAR(100) NOT NULL,
    AccountNumber VARCHAR(50) NOT NULL,
    Currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    CurrentBalance DECIMAL(18,2) NOT NULL DEFAULT 0,
    LinkedAccountId INT REFERENCES Accounts(Id),
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS BankReconciliations (
    Id SERIAL PRIMARY KEY,
    BankAccountId INT REFERENCES BankAccounts(Id),
    StatementDate TIMESTAMP NOT NULL,
    StatementBalance DECIMAL(18,2) NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    Notes TEXT,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS BankReconciliationDetails (
    Id SERIAL PRIMARY KEY,
    BankReconciliationId INT REFERENCES BankReconciliations(Id),
    JournalEntryDetailId INT, -- References JournalEntryDetails
    IsCleared BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

-- Company Settings
CREATE TABLE IF NOT EXISTS CompanySettings (
    Id SERIAL PRIMARY KEY,
    CompanyName VARCHAR(100) NOT NULL DEFAULT 'Mi Empresa',
    Address VARCHAR(255),
    Phone VARCHAR(50),
    Email VARCHAR(100),
    TaxPercentage DECIMAL(5,2) NOT NULL DEFAULT 15.00,
    StoreTheme VARCHAR(50) DEFAULT 'minimalist',
    ShowStoreSlider BOOLEAN DEFAULT true,
    StoreProductsPerPage INT DEFAULT 12,
    ActiveThemeId INT,
    SliderImage1 VARCHAR(500),
    SliderImage2 VARCHAR(500),
    SliderImage3 VARCHAR(500),
    SocialSecurityPercentage DECIMAL(5,2) NOT NULL DEFAULT 0,
    AfpPercentage DECIMAL(5,2) NOT NULL DEFAULT 0,
    UpdatedAt TIMESTAMP
);

-- HR
CREATE TABLE IF NOT EXISTS Attendances (
    Id SERIAL PRIMARY KEY,
    UserId INT REFERENCES Users(Id),
    Date TIMESTAMP NOT NULL,
    CheckInTime TIME,
    CheckOutTime TIME,
    Status VARCHAR(20) NOT NULL DEFAULT 'Present',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS PayrollRuns (
    Id SERIAL PRIMARY KEY,
    PeriodStart TIMESTAMP NOT NULL,
    PeriodEnd TIMESTAMP NOT NULL,
    ProcessedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Notes TEXT,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS PayrollDetails (
    Id SERIAL PRIMARY KEY,
    PayrollRunId INT REFERENCES PayrollRuns(Id),
    UserId INT REFERENCES Users(Id),
    BaseSalary DECIMAL(12,2) NOT NULL,
    ExtraHoursAmount DECIMAL(12,2) NOT NULL DEFAULT 0,
    BonusAmount DECIMAL(12,2) NOT NULL DEFAULT 0,
    DeductionsAmount DECIMAL(12,2) NOT NULL DEFAULT 0,
    NetPay DECIMAL(12,2) NOT NULL,
    Observations TEXT,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

-- Coupons
CREATE TABLE IF NOT EXISTS Coupons (
    Id SERIAL PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    DiscountPercentage DECIMAL(5,2),
    DiscountAmount DECIMAL(12,2),
    ValidFrom TIMESTAMP,
    ValidUntil TIMESTAMP,
    MaxUses INT,
    CurrentUses INT NOT NULL DEFAULT 0,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

-- BranchMovements additions
ALTER TABLE BranchMovements 
ADD COLUMN IF NOT EXISTS CashRegisterId INT,
ADD COLUMN IF NOT EXISTS AccountId INT,
ADD COLUMN IF NOT EXISTS PaymentMethod VARCHAR(20) DEFAULT 'CASH';

-- JournalEntryDetails additions
ALTER TABLE JournalEntryDetails
ADD COLUMN IF NOT EXISTS AccountId INT;

-- Other Missing Columns
ALTER TABLE Branches
ADD COLUMN IF NOT EXISTS AvailableFunds DECIMAL(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS Status VARCHAR(20) DEFAULT 'OPEN';

ALTER TABLE Orders
ADD COLUMN IF NOT EXISTS PaymentMethod VARCHAR(20);

ALTER TABLE OrderDetails
ADD COLUMN IF NOT EXISTS ProductName VARCHAR(100);

ALTER TABLE Products
ADD COLUMN IF NOT EXISTS IsTaxExempt BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS ImageUrl VARCHAR(500);

ALTER TABLE Purchases
ADD COLUMN IF NOT EXISTS BranchId INT REFERENCES Branches(Id);

ALTER TABLE Sales
ADD COLUMN IF NOT EXISTS TaxAmount DECIMAL(12,2) DEFAULT 0;

-- Fleet Management
CREATE TABLE IF NOT EXISTS Vehicles (
    Id SERIAL PRIMARY KEY,
    PlateNumber VARCHAR(20) NOT NULL,
    Model VARCHAR(100) NOT NULL,
    Capacity DECIMAL(10,2),
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS Drivers (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    LicenseNumber VARCHAR(50) NOT NULL,
    Phone VARCHAR(50),
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS DeliveryRoutes (
    Id SERIAL PRIMARY KEY,
    Date TIMESTAMP NOT NULL,
    DriverId INT REFERENCES Drivers(Id),
    VehicleId INT REFERENCES Vehicles(Id),
    BranchId INT REFERENCES Branches(Id),
    Status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS RouteStops (
    Id SERIAL PRIMARY KEY,
    DeliveryRouteId INT REFERENCES DeliveryRoutes(Id),
    OrderId INT REFERENCES Orders(Id),
    StopOrder INT NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    EstimatedTime TIMESTAMP,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);
